### ISSUE TITLE
[Feature]: Starting CorefluxCentral with arguments

### ISSUE THREAD

**Issue by nunocgoncalves** [CorefluxCommunity/Coreflux-roadmap#20]
### Tell us about your request

I'd like to be able to execute the ``CorefluxCentral`` binary with arguments to create the daemon service, to parse the broker config and user list.

### Which component(s) is this request for?

- [X] Coreflux Broker
- [ ] Coreflux Hub
- [ ] Flux Assets
- [ ] Flux Language
- [ ] Power Ups
- [ ] User Experience (UX)
- [ ] Documentation
- [ ] Conceptual Features

### Is your feature request related to a problem? Please describe.

As of right now, it is challenging to set up the Coreflux Broker programmatically for production. For example, setting the certificate's path and password requires me to connect to the broker, change the config and restart the broker.

### Describe the solution you'd like

Here are my proposed argument flags:
``-i`` -> to install the daemon service
``-c`` -> to parse the broker config
``-u`` -> to parse the user list

Additionally, it would be great if the broker was aware of an existing daemon service, broker config and user list and ignore the arguments in that case. And, if for some reason any of those needs to be overridden, a force flag ``-f`` could be used.

**Comment by HugoAVaz** [comment]
This ideia actually conflicts with the current -I . Check how to [Install Coreflux MQTT Broker](https://docs.coreflux.org/getting-started/installation-hubless/). But I would suggest adding the extended version as well:

`-i  | --install` - in order to install has a daemon service /  windows service (replace the original -I )
`-c | --config <jsonfile>` - to provide a config to start the broker  if the broker doesn't have a config
`-u | --user <jsonfile>` - to provide a user list to start the broker  if the broker doesn't have a user list
`-f | --force` - if present the force command with start and replace the existing configuration

**Comment by nunocgoncalves** [comment]
I didn't know the ``-i`` flag already existed. Having both short and long flags would be great!

**Comment by HugoAVaz** [comment]
The version 1.2.010 is already packed with this feature. We will document this for the future releases under docs.
